name: 莓墙
description: Blog for 王颖博
meta_description: "Hi, I'm yingbo.wang, an iOS coder, now work in beijing”

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://wangyingbo.top'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            ‘wangyingbo.top’
author:         ‘yingbo.wang’
