#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "王颖博"
email: wangyingbo528@126.com
description: "莓墙"
keywords: "莓墙"

# 用户信息设置
weibo_username: 王颖博
github_username: wangyingbo

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置http://wangyingbo.top
url: "wangyingbo.top"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
duoshuo_shortname: http://duoshuo.com/creat-site/wangyingbo.top

# 百度统计设置
# baidu_analysis:
